sudo: false
language: rust
jobs:
  include:
    - os: windows
      rust: stable

    - os: osx
      rust: stable

    - os: linux
      rust: stable

env:
  - RUSTFLAGS="-Ctarget-feature=+aes,+ssse3" RUSTDOCFLAGS="-Ctarget-feature=+aes,+ssse3" RUST_BACKTRACE=1