on: [push]


name: mipsel build

jobs:
  linux_arm7:
    name: Linux mipsel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: mipsel-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target mipsel-unknown-linux-gnu
